openapi: 3.0.0
info:
  description: Interface that models the operations available for ProntoGram in ACMESky.
  title: ProntoGram
  version: "1.0"
servers:
- url: http://localhost:3000
paths:
  /messages:
    post:
      description: |-
        Sends the message to ProntoGram for being dispatched to the actual user.
        API for: ACMESky
      operationId: send_message
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
      responses:
        "200":
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad Request
      summary: sendMessage
      x-openapi-router-controller: prontogram.controllers.default_controller
components:
  schemas:
    Message:
      example:
        receiver: receiver
        sender: sender
        body: body
      properties:
        sender:
          minLength: 1
          type: string
        receiver:
          minLength: 1
          type: string
        body:
          minLength: 1
          type: string
      required:
      - body
      - receiver
      - sender
      title: Message
      type: object
    Error:
      properties:
        description:
          minLength: 1
          type: string
      required:
      - description
      title: Error
      type: object
